/* eslint-disable import/no-extraneous-dependencies */
import { defineConfig } from "tsup";

export default defineConfig({
  clean: true,
  dts: true,
  entry: [
    "src/astro.ts",
    "src/bun.ts",
    "src/cloudflare.ts",
    "src/connect.ts",
    "src/deno/fresh.ts",
    "src/digitalocean.ts",
    "src/edge.ts",
    "src/experimental.ts",
    "src/express.ts",
    "src/fastify.ts",
    "src/h3.ts",
    "src/hono.ts",
    "src/index.ts",
    "src/koa.ts",
    "src/lambda.ts",
    "src/next.ts",
    "src/nitro.ts",
    "src/node.ts",
    "src/nuxt.ts",
    "src/redwood.ts",
    "src/remix.ts",
    "src/sveltekit.ts",
    "src/types.ts",
    "!src/test/**/*",
    "!src/**/*.test.*",
  ],
  format: ["cjs", "esm"],
  outDir: "dist",
  tsconfig: "tsconfig.build.json",
  sourcemap: true,
});
