name: "Ensure CI image"
description: "Ensure the CI Docker image exists for this deps hash"
outputs:
  image:
    description: "The container image URL"
    value: ${{ steps.meta.outputs.image }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - id: hash
      shell: bash
      run: |
        HASH=$(sha256sum flake.nix flake.lock pnpm-lock.yaml | sha256sum | cut -d' ' -f1)
        echo "hash=$HASH" >> "$GITHUB_OUTPUT"

    - id: meta
      shell: bash
      run: |
        IMAGE="ghcr.io/${{ github.repository }}/ci:${{ steps.hash.outputs.hash }}"
        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"

    - name: Try pull existing
      shell: bash
      run: docker pull ${{ steps.meta.outputs.image }} || echo "missing"

    - name: Build + push if missing
      if: failure()
      shell: bash
      run: |
        nix build .#ciImage
        docker load < result
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag inngest-ci:latest ${{ steps.meta.outputs.image }}
        docker push ${{ steps.meta.outputs.image }}
