name: "Setup and build inngest"
description: "Sets up Node, installs dependencies, and builds the inngest package."
inputs:
  working-directory: # id of input
    description: "The directory to run the action in."
    required: false
    default: "."
  install-dependencies:
    description: "Whether dependencies should be installed."
    required: false
    default: true
  build:
    description: "Whether the build step should be run."
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: nicknovitski/nix-develop@v1

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: pnpm install --frozen-lockfile
      shell: nix develop --command bash -e {0}
      working-directory: ${{ inputs.working-directory }}

    - name: Build test dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: pnpm run build
      shell: nix develop --command bash -e {0}
      working-directory: ${{ inputs.working-directory }}/packages/test

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: pnpm run build
      shell: nix develop --command bash -e {0}
      working-directory: ${{ inputs.working-directory }}/packages/inngest
