name: "Setup and build inngest"
description: "Sets up Node, installs dependencies, and builds the inngest package."
inputs:
  working-directory:  # id of input
    description: 'The directory to run the action in.'
    required: false
    default: '.'
  install-dependencies:
    description: 'Whether dependencies should be installed.'
    required: false
    default: true
  build:
    description: 'Whether the build step should be run.'
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: "8.6.2"
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - run: npm i -g @antfu/ni
      shell: bash

    - uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: pnpm install
      shell: bash
      working-directory: ${{ inputs.working-directory }}/packages/inngest

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: pnpm run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}/packages/inngest
