name: "Setup and build"
description: "Sets up Node, installs dependencies, and builds the project."
runs:
  using: composite
  steps:
    - uses: volta-cli/action@v4

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - shell: bash
      run: yarn install --frozen-lockfile

    - shell: bash
      run: yarn install --frozen-lockfile
      working-directory: landing

    - shell: bash
      run: yarn build
