name: "Setup and build"
description: "Sets up Node, installs dependencies, and builds the project."
inputs:
  working-directory:  # id of input
    description: 'The directory to run the action in.'
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - uses: volta-cli/action@v4

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"
      working-directory: ${{ inputs.working-directory }}

    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - shell: bash
      run: yarn install --frozen-lockfile
      working-directory: ${{ inputs.working-directory }}

    - shell: bash
      run: yarn install --frozen-lockfile
      working-directory: ${{ inputs.working-directory }}/landing

    - shell: bash
      run: yarn build
      working-directory: ${{ inputs.working-directory }}
