name: "Setup CI env"
description: "Install Node, restore pnpm cache, install deps"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - run: pnpm install --frozen-lockfile
      shell: bash
