name: "Setup CI env"
description: "Restore pnpm cache and install deps"
runs:
  using: "composite"
  steps:
    - name: Restore pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - run: pnpm install --frozen-lockfile
      shell: bash
