name: "Setup CI env"
description: "Fetch pnpm deps and install offline"
runs:
  using: "composite"
  steps:
    - name: Restore pnpm fetch cache
      uses: actions/cache@v4
      with:
        path: .pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Fetch deps
      shell: bash
      run: pnpm fetch --store-dir .pnpm-store

    - name: Install offline
      shell: bash
      run: pnpm install --frozen-lockfile --offline --store-dir .pnpm-store
