name = "framework-hono"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# [vars]
# MY_VAR = "my-variable"

# Inngest+Cloudflare Worker "Cloud" mode:
# If using "cloud" mode with wrangler you'll have to use ngrok or similar
# As your cloud worker cannot reach the Inngest Dev Server running on localhost
# INNGEST_DEV="https://<replace-this>.ngrok-free.app"
# Also when using "cloud" mode during dev, you may need to also configure
# your serve URL to tell the Inngest Dev Server to use the localhost URL instead
# wrangler's public URL
# INNGEST_SERVE_HOST="http://localhost:8787"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"