// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.6
// source: src/components/sdkFeatureObservations/protobuf/feature_observations.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sdk_feature_observations.v1";

export enum OTelProviderSource {
  OTEL_PROVIDER_SOURCE_UNSPECIFIED = 0,
  OTEL_PROVIDER_SOURCE_FIRST_PARTY = 1,
  OTEL_PROVIDER_SOURCE_USER_PROVIDED = 2,
  OTEL_PROVIDER_SOURCE_LEGACY_SDK = 3,
  UNRECOGNIZED = -1,
}

export function oTelProviderSourceFromJSON(object: any): OTelProviderSource {
  switch (object) {
    case 0:
    case "OTEL_PROVIDER_SOURCE_UNSPECIFIED":
      return OTelProviderSource.OTEL_PROVIDER_SOURCE_UNSPECIFIED;
    case 1:
    case "OTEL_PROVIDER_SOURCE_FIRST_PARTY":
      return OTelProviderSource.OTEL_PROVIDER_SOURCE_FIRST_PARTY;
    case 2:
    case "OTEL_PROVIDER_SOURCE_USER_PROVIDED":
      return OTelProviderSource.OTEL_PROVIDER_SOURCE_USER_PROVIDED;
    case 3:
    case "OTEL_PROVIDER_SOURCE_LEGACY_SDK":
      return OTelProviderSource.OTEL_PROVIDER_SOURCE_LEGACY_SDK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OTelProviderSource.UNRECOGNIZED;
  }
}

export function oTelProviderSourceToJSON(object: OTelProviderSource): string {
  switch (object) {
    case OTelProviderSource.OTEL_PROVIDER_SOURCE_UNSPECIFIED:
      return "OTEL_PROVIDER_SOURCE_UNSPECIFIED";
    case OTelProviderSource.OTEL_PROVIDER_SOURCE_FIRST_PARTY:
      return "OTEL_PROVIDER_SOURCE_FIRST_PARTY";
    case OTelProviderSource.OTEL_PROVIDER_SOURCE_USER_PROVIDED:
      return "OTEL_PROVIDER_SOURCE_USER_PROVIDED";
    case OTelProviderSource.OTEL_PROVIDER_SOURCE_LEGACY_SDK:
      return "OTEL_PROVIDER_SOURCE_LEGACY_SDK";
    case OTelProviderSource.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OTelSetupPath {
  OTEL_SETUP_PATH_UNSPECIFIED = 0,
  OTEL_SETUP_PATH_EXTEND_EXISTING_PROVIDER = 1,
  OTEL_SETUP_PATH_LEGACY_CREATE_PROVIDER = 2,
  UNRECOGNIZED = -1,
}

export function oTelSetupPathFromJSON(object: any): OTelSetupPath {
  switch (object) {
    case 0:
    case "OTEL_SETUP_PATH_UNSPECIFIED":
      return OTelSetupPath.OTEL_SETUP_PATH_UNSPECIFIED;
    case 1:
    case "OTEL_SETUP_PATH_EXTEND_EXISTING_PROVIDER":
      return OTelSetupPath.OTEL_SETUP_PATH_EXTEND_EXISTING_PROVIDER;
    case 2:
    case "OTEL_SETUP_PATH_LEGACY_CREATE_PROVIDER":
      return OTelSetupPath.OTEL_SETUP_PATH_LEGACY_CREATE_PROVIDER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OTelSetupPath.UNRECOGNIZED;
  }
}

export function oTelSetupPathToJSON(object: OTelSetupPath): string {
  switch (object) {
    case OTelSetupPath.OTEL_SETUP_PATH_UNSPECIFIED:
      return "OTEL_SETUP_PATH_UNSPECIFIED";
    case OTelSetupPath.OTEL_SETUP_PATH_EXTEND_EXISTING_PROVIDER:
      return "OTEL_SETUP_PATH_EXTEND_EXISTING_PROVIDER";
    case OTelSetupPath.OTEL_SETUP_PATH_LEGACY_CREATE_PROVIDER:
      return "OTEL_SETUP_PATH_LEGACY_CREATE_PROVIDER";
    case OTelSetupPath.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OTelSetupFailure {
  OTEL_SETUP_FAILURE_UNSPECIFIED = 0,
  OTEL_SETUP_FAILURE_NO_PROVIDER = 1,
  OTEL_SETUP_FAILURE_NOT_ADDED = 2,
  OTEL_SETUP_FAILURE_PROVIDER_CREATION_FAILED = 3,
  OTEL_SETUP_FAILURE_UNKNOWN_ERROR = 4,
  UNRECOGNIZED = -1,
}

export function oTelSetupFailureFromJSON(object: any): OTelSetupFailure {
  switch (object) {
    case 0:
    case "OTEL_SETUP_FAILURE_UNSPECIFIED":
      return OTelSetupFailure.OTEL_SETUP_FAILURE_UNSPECIFIED;
    case 1:
    case "OTEL_SETUP_FAILURE_NO_PROVIDER":
      return OTelSetupFailure.OTEL_SETUP_FAILURE_NO_PROVIDER;
    case 2:
    case "OTEL_SETUP_FAILURE_NOT_ADDED":
      return OTelSetupFailure.OTEL_SETUP_FAILURE_NOT_ADDED;
    case 3:
    case "OTEL_SETUP_FAILURE_PROVIDER_CREATION_FAILED":
      return OTelSetupFailure.OTEL_SETUP_FAILURE_PROVIDER_CREATION_FAILED;
    case 4:
    case "OTEL_SETUP_FAILURE_UNKNOWN_ERROR":
      return OTelSetupFailure.OTEL_SETUP_FAILURE_UNKNOWN_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OTelSetupFailure.UNRECOGNIZED;
  }
}

export function oTelSetupFailureToJSON(object: OTelSetupFailure): string {
  switch (object) {
    case OTelSetupFailure.OTEL_SETUP_FAILURE_UNSPECIFIED:
      return "OTEL_SETUP_FAILURE_UNSPECIFIED";
    case OTelSetupFailure.OTEL_SETUP_FAILURE_NO_PROVIDER:
      return "OTEL_SETUP_FAILURE_NO_PROVIDER";
    case OTelSetupFailure.OTEL_SETUP_FAILURE_NOT_ADDED:
      return "OTEL_SETUP_FAILURE_NOT_ADDED";
    case OTelSetupFailure.OTEL_SETUP_FAILURE_PROVIDER_CREATION_FAILED:
      return "OTEL_SETUP_FAILURE_PROVIDER_CREATION_FAILED";
    case OTelSetupFailure.OTEL_SETUP_FAILURE_UNKNOWN_ERROR:
      return "OTEL_SETUP_FAILURE_UNKNOWN_ERROR";
    case OTelSetupFailure.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum AIMetadataExtractionReadinessReason {
  AI_METADATA_EXTRACTION_READINESS_REASON_UNSPECIFIED = 0,
  AI_METADATA_EXTRACTION_READINESS_REASON_READY = 1,
  AI_METADATA_EXTRACTION_READINESS_REASON_DISABLED_BY_USER = 2,
  AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_PROVIDER_MISSING = 3,
  AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED = 4,
  UNRECOGNIZED = -1,
}

export function aIMetadataExtractionReadinessReasonFromJSON(object: any): AIMetadataExtractionReadinessReason {
  switch (object) {
    case 0:
    case "AI_METADATA_EXTRACTION_READINESS_REASON_UNSPECIFIED":
      return AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_UNSPECIFIED;
    case 1:
    case "AI_METADATA_EXTRACTION_READINESS_REASON_READY":
      return AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_READY;
    case 2:
    case "AI_METADATA_EXTRACTION_READINESS_REASON_DISABLED_BY_USER":
      return AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_DISABLED_BY_USER;
    case 3:
    case "AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_PROVIDER_MISSING":
      return AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_PROVIDER_MISSING;
    case 4:
    case "AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED":
      return AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AIMetadataExtractionReadinessReason.UNRECOGNIZED;
  }
}

export function aIMetadataExtractionReadinessReasonToJSON(object: AIMetadataExtractionReadinessReason): string {
  switch (object) {
    case AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_UNSPECIFIED:
      return "AI_METADATA_EXTRACTION_READINESS_REASON_UNSPECIFIED";
    case AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_READY:
      return "AI_METADATA_EXTRACTION_READINESS_REASON_READY";
    case AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_DISABLED_BY_USER:
      return "AI_METADATA_EXTRACTION_READINESS_REASON_DISABLED_BY_USER";
    case AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_PROVIDER_MISSING:
      return "AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_PROVIDER_MISSING";
    case AIMetadataExtractionReadinessReason.AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED:
      return "AI_METADATA_EXTRACTION_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED";
    case AIMetadataExtractionReadinessReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ExtendedTracesReadinessReason {
  EXTENDED_TRACES_READINESS_REASON_UNSPECIFIED = 0,
  EXTENDED_TRACES_READINESS_REASON_READY = 1,
  EXTENDED_TRACES_READINESS_REASON_NOT_ENABLED_BY_USER = 2,
  EXTENDED_TRACES_READINESS_REASON_DISABLED_BY_USER = 3,
  EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_MISSING = 4,
  EXTENDED_TRACES_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED = 5,
  EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_CREATION_FAILED = 6,
  UNRECOGNIZED = -1,
}

export function extendedTracesReadinessReasonFromJSON(object: any): ExtendedTracesReadinessReason {
  switch (object) {
    case 0:
    case "EXTENDED_TRACES_READINESS_REASON_UNSPECIFIED":
      return ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_UNSPECIFIED;
    case 1:
    case "EXTENDED_TRACES_READINESS_REASON_READY":
      return ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_READY;
    case 2:
    case "EXTENDED_TRACES_READINESS_REASON_NOT_ENABLED_BY_USER":
      return ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_NOT_ENABLED_BY_USER;
    case 3:
    case "EXTENDED_TRACES_READINESS_REASON_DISABLED_BY_USER":
      return ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_DISABLED_BY_USER;
    case 4:
    case "EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_MISSING":
      return ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_MISSING;
    case 5:
    case "EXTENDED_TRACES_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED":
      return ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED;
    case 6:
    case "EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_CREATION_FAILED":
      return ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_CREATION_FAILED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExtendedTracesReadinessReason.UNRECOGNIZED;
  }
}

export function extendedTracesReadinessReasonToJSON(object: ExtendedTracesReadinessReason): string {
  switch (object) {
    case ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_UNSPECIFIED:
      return "EXTENDED_TRACES_READINESS_REASON_UNSPECIFIED";
    case ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_READY:
      return "EXTENDED_TRACES_READINESS_REASON_READY";
    case ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_NOT_ENABLED_BY_USER:
      return "EXTENDED_TRACES_READINESS_REASON_NOT_ENABLED_BY_USER";
    case ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_DISABLED_BY_USER:
      return "EXTENDED_TRACES_READINESS_REASON_DISABLED_BY_USER";
    case ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_MISSING:
      return "EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_MISSING";
    case ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED:
      return "EXTENDED_TRACES_READINESS_REASON_OTEL_SPAN_PROCESSOR_NOT_ADDED";
    case ExtendedTracesReadinessReason.EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_CREATION_FAILED:
      return "EXTENDED_TRACES_READINESS_REASON_OTEL_PROVIDER_CREATION_FAILED";
    case ExtendedTracesReadinessReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ExtendedTracesBehavior {
  EXTENDED_TRACES_BEHAVIOR_UNSPECIFIED = 0,
  EXTENDED_TRACES_BEHAVIOR_EXTEND_PROVIDER = 1,
  EXTENDED_TRACES_BEHAVIOR_OFF = 2,
  EXTENDED_TRACES_BEHAVIOR_AUTO = 3,
  EXTENDED_TRACES_BEHAVIOR_CREATE_PROVIDER = 4,
  EXTENDED_TRACES_BEHAVIOR_UNKNOWN = 5,
  UNRECOGNIZED = -1,
}

export function extendedTracesBehaviorFromJSON(object: any): ExtendedTracesBehavior {
  switch (object) {
    case 0:
    case "EXTENDED_TRACES_BEHAVIOR_UNSPECIFIED":
      return ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_UNSPECIFIED;
    case 1:
    case "EXTENDED_TRACES_BEHAVIOR_EXTEND_PROVIDER":
      return ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_EXTEND_PROVIDER;
    case 2:
    case "EXTENDED_TRACES_BEHAVIOR_OFF":
      return ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_OFF;
    case 3:
    case "EXTENDED_TRACES_BEHAVIOR_AUTO":
      return ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_AUTO;
    case 4:
    case "EXTENDED_TRACES_BEHAVIOR_CREATE_PROVIDER":
      return ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_CREATE_PROVIDER;
    case 5:
    case "EXTENDED_TRACES_BEHAVIOR_UNKNOWN":
      return ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_UNKNOWN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ExtendedTracesBehavior.UNRECOGNIZED;
  }
}

export function extendedTracesBehaviorToJSON(object: ExtendedTracesBehavior): string {
  switch (object) {
    case ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_UNSPECIFIED:
      return "EXTENDED_TRACES_BEHAVIOR_UNSPECIFIED";
    case ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_EXTEND_PROVIDER:
      return "EXTENDED_TRACES_BEHAVIOR_EXTEND_PROVIDER";
    case ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_OFF:
      return "EXTENDED_TRACES_BEHAVIOR_OFF";
    case ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_AUTO:
      return "EXTENDED_TRACES_BEHAVIOR_AUTO";
    case ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_CREATE_PROVIDER:
      return "EXTENDED_TRACES_BEHAVIOR_CREATE_PROVIDER";
    case ExtendedTracesBehavior.EXTENDED_TRACES_BEHAVIOR_UNKNOWN:
      return "EXTENDED_TRACES_BEHAVIOR_UNKNOWN";
    case ExtendedTracesBehavior.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SendEventsReadinessReason {
  SEND_EVENTS_READINESS_REASON_UNSPECIFIED = 0,
  SEND_EVENTS_READINESS_REASON_READY = 1,
  SEND_EVENTS_READINESS_REASON_EVENT_KEY_MISSING = 2,
  UNRECOGNIZED = -1,
}

export function sendEventsReadinessReasonFromJSON(object: any): SendEventsReadinessReason {
  switch (object) {
    case 0:
    case "SEND_EVENTS_READINESS_REASON_UNSPECIFIED":
      return SendEventsReadinessReason.SEND_EVENTS_READINESS_REASON_UNSPECIFIED;
    case 1:
    case "SEND_EVENTS_READINESS_REASON_READY":
      return SendEventsReadinessReason.SEND_EVENTS_READINESS_REASON_READY;
    case 2:
    case "SEND_EVENTS_READINESS_REASON_EVENT_KEY_MISSING":
      return SendEventsReadinessReason.SEND_EVENTS_READINESS_REASON_EVENT_KEY_MISSING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SendEventsReadinessReason.UNRECOGNIZED;
  }
}

export function sendEventsReadinessReasonToJSON(object: SendEventsReadinessReason): string {
  switch (object) {
    case SendEventsReadinessReason.SEND_EVENTS_READINESS_REASON_UNSPECIFIED:
      return "SEND_EVENTS_READINESS_REASON_UNSPECIFIED";
    case SendEventsReadinessReason.SEND_EVENTS_READINESS_REASON_READY:
      return "SEND_EVENTS_READINESS_REASON_READY";
    case SendEventsReadinessReason.SEND_EVENTS_READINESS_REASON_EVENT_KEY_MISSING:
      return "SEND_EVENTS_READINESS_REASON_EVENT_KEY_MISSING";
    case SendEventsReadinessReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FeatureObservation {
  aiMetadataExtraction?: AIMetadataExtraction | undefined;
  extendedTraces?: ExtendedTraces | undefined;
  sendEvents?: SendEvents | undefined;
}

export interface OTelSetup {
  path: OTelSetupPath;
  providerFound: boolean;
  providerSource: OTelProviderSource;
  addSpanProcessorAttempted: boolean;
  spanProcessorAdded: boolean;
  failure: OTelSetupFailure;
}

export interface AIMetadataExtraction {
  readinessReason: AIMetadataExtractionReadinessReason;
  otelSetup: OTelSetup | undefined;
}

export interface ExtendedTraces {
  readinessReason: ExtendedTracesReadinessReason;
  config: ExtendedTracesConfig | undefined;
  otelSetup: OTelSetup | undefined;
}

export interface ExtendedTracesConfig {
  behavior: ExtendedTracesBehavior;
}

export interface SendEvents {
  readinessReason: SendEventsReadinessReason;
  config: SendEventsConfig | undefined;
}

export interface SendEventsConfig {
  hasEventKey: boolean;
  hasEventApiOriginOverride: boolean;
}

function createBaseFeatureObservation(): FeatureObservation {
  return { aiMetadataExtraction: undefined, extendedTraces: undefined, sendEvents: undefined };
}

export const FeatureObservation: MessageFns<FeatureObservation> = {
  encode(message: FeatureObservation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.aiMetadataExtraction !== undefined) {
      AIMetadataExtraction.encode(message.aiMetadataExtraction, writer.uint32(10).fork()).join();
    }
    if (message.extendedTraces !== undefined) {
      ExtendedTraces.encode(message.extendedTraces, writer.uint32(18).fork()).join();
    }
    if (message.sendEvents !== undefined) {
      SendEvents.encode(message.sendEvents, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeatureObservation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeatureObservation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.aiMetadataExtraction = AIMetadataExtraction.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.extendedTraces = ExtendedTraces.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sendEvents = SendEvents.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FeatureObservation {
    return {
      aiMetadataExtraction: isSet(object.aiMetadataExtraction)
        ? AIMetadataExtraction.fromJSON(object.aiMetadataExtraction)
        : undefined,
      extendedTraces: isSet(object.extendedTraces) ? ExtendedTraces.fromJSON(object.extendedTraces) : undefined,
      sendEvents: isSet(object.sendEvents) ? SendEvents.fromJSON(object.sendEvents) : undefined,
    };
  },

  toJSON(message: FeatureObservation): unknown {
    const obj: any = {};
    if (message.aiMetadataExtraction !== undefined) {
      obj.aiMetadataExtraction = AIMetadataExtraction.toJSON(message.aiMetadataExtraction);
    }
    if (message.extendedTraces !== undefined) {
      obj.extendedTraces = ExtendedTraces.toJSON(message.extendedTraces);
    }
    if (message.sendEvents !== undefined) {
      obj.sendEvents = SendEvents.toJSON(message.sendEvents);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FeatureObservation>, I>>(base?: I): FeatureObservation {
    return FeatureObservation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FeatureObservation>, I>>(object: I): FeatureObservation {
    const message = createBaseFeatureObservation();
    message.aiMetadataExtraction = (object.aiMetadataExtraction !== undefined && object.aiMetadataExtraction !== null)
      ? AIMetadataExtraction.fromPartial(object.aiMetadataExtraction)
      : undefined;
    message.extendedTraces = (object.extendedTraces !== undefined && object.extendedTraces !== null)
      ? ExtendedTraces.fromPartial(object.extendedTraces)
      : undefined;
    message.sendEvents = (object.sendEvents !== undefined && object.sendEvents !== null)
      ? SendEvents.fromPartial(object.sendEvents)
      : undefined;
    return message;
  },
};

function createBaseOTelSetup(): OTelSetup {
  return {
    path: 0,
    providerFound: false,
    providerSource: 0,
    addSpanProcessorAttempted: false,
    spanProcessorAdded: false,
    failure: 0,
  };
}

export const OTelSetup: MessageFns<OTelSetup> = {
  encode(message: OTelSetup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== 0) {
      writer.uint32(8).int32(message.path);
    }
    if (message.providerFound !== false) {
      writer.uint32(16).bool(message.providerFound);
    }
    if (message.providerSource !== 0) {
      writer.uint32(24).int32(message.providerSource);
    }
    if (message.addSpanProcessorAttempted !== false) {
      writer.uint32(32).bool(message.addSpanProcessorAttempted);
    }
    if (message.spanProcessorAdded !== false) {
      writer.uint32(40).bool(message.spanProcessorAdded);
    }
    if (message.failure !== 0) {
      writer.uint32(48).int32(message.failure);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OTelSetup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOTelSetup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.path = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.providerFound = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.providerSource = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.addSpanProcessorAttempted = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.spanProcessorAdded = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.failure = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OTelSetup {
    return {
      path: isSet(object.path) ? oTelSetupPathFromJSON(object.path) : 0,
      providerFound: isSet(object.providerFound) ? globalThis.Boolean(object.providerFound) : false,
      providerSource: isSet(object.providerSource) ? oTelProviderSourceFromJSON(object.providerSource) : 0,
      addSpanProcessorAttempted: isSet(object.addSpanProcessorAttempted)
        ? globalThis.Boolean(object.addSpanProcessorAttempted)
        : false,
      spanProcessorAdded: isSet(object.spanProcessorAdded) ? globalThis.Boolean(object.spanProcessorAdded) : false,
      failure: isSet(object.failure) ? oTelSetupFailureFromJSON(object.failure) : 0,
    };
  },

  toJSON(message: OTelSetup): unknown {
    const obj: any = {};
    if (message.path !== 0) {
      obj.path = oTelSetupPathToJSON(message.path);
    }
    if (message.providerFound !== false) {
      obj.providerFound = message.providerFound;
    }
    if (message.providerSource !== 0) {
      obj.providerSource = oTelProviderSourceToJSON(message.providerSource);
    }
    if (message.addSpanProcessorAttempted !== false) {
      obj.addSpanProcessorAttempted = message.addSpanProcessorAttempted;
    }
    if (message.spanProcessorAdded !== false) {
      obj.spanProcessorAdded = message.spanProcessorAdded;
    }
    if (message.failure !== 0) {
      obj.failure = oTelSetupFailureToJSON(message.failure);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OTelSetup>, I>>(base?: I): OTelSetup {
    return OTelSetup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OTelSetup>, I>>(object: I): OTelSetup {
    const message = createBaseOTelSetup();
    message.path = object.path ?? 0;
    message.providerFound = object.providerFound ?? false;
    message.providerSource = object.providerSource ?? 0;
    message.addSpanProcessorAttempted = object.addSpanProcessorAttempted ?? false;
    message.spanProcessorAdded = object.spanProcessorAdded ?? false;
    message.failure = object.failure ?? 0;
    return message;
  },
};

function createBaseAIMetadataExtraction(): AIMetadataExtraction {
  return { readinessReason: 0, otelSetup: undefined };
}

export const AIMetadataExtraction: MessageFns<AIMetadataExtraction> = {
  encode(message: AIMetadataExtraction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.readinessReason !== 0) {
      writer.uint32(8).int32(message.readinessReason);
    }
    if (message.otelSetup !== undefined) {
      OTelSetup.encode(message.otelSetup, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AIMetadataExtraction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAIMetadataExtraction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.readinessReason = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.otelSetup = OTelSetup.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AIMetadataExtraction {
    return {
      readinessReason: isSet(object.readinessReason)
        ? aIMetadataExtractionReadinessReasonFromJSON(object.readinessReason)
        : 0,
      otelSetup: isSet(object.otelSetup) ? OTelSetup.fromJSON(object.otelSetup) : undefined,
    };
  },

  toJSON(message: AIMetadataExtraction): unknown {
    const obj: any = {};
    if (message.readinessReason !== 0) {
      obj.readinessReason = aIMetadataExtractionReadinessReasonToJSON(message.readinessReason);
    }
    if (message.otelSetup !== undefined) {
      obj.otelSetup = OTelSetup.toJSON(message.otelSetup);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AIMetadataExtraction>, I>>(base?: I): AIMetadataExtraction {
    return AIMetadataExtraction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AIMetadataExtraction>, I>>(object: I): AIMetadataExtraction {
    const message = createBaseAIMetadataExtraction();
    message.readinessReason = object.readinessReason ?? 0;
    message.otelSetup = (object.otelSetup !== undefined && object.otelSetup !== null)
      ? OTelSetup.fromPartial(object.otelSetup)
      : undefined;
    return message;
  },
};

function createBaseExtendedTraces(): ExtendedTraces {
  return { readinessReason: 0, config: undefined, otelSetup: undefined };
}

export const ExtendedTraces: MessageFns<ExtendedTraces> = {
  encode(message: ExtendedTraces, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.readinessReason !== 0) {
      writer.uint32(8).int32(message.readinessReason);
    }
    if (message.config !== undefined) {
      ExtendedTracesConfig.encode(message.config, writer.uint32(18).fork()).join();
    }
    if (message.otelSetup !== undefined) {
      OTelSetup.encode(message.otelSetup, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExtendedTraces {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExtendedTraces();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.readinessReason = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = ExtendedTracesConfig.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.otelSetup = OTelSetup.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExtendedTraces {
    return {
      readinessReason: isSet(object.readinessReason)
        ? extendedTracesReadinessReasonFromJSON(object.readinessReason)
        : 0,
      config: isSet(object.config) ? ExtendedTracesConfig.fromJSON(object.config) : undefined,
      otelSetup: isSet(object.otelSetup) ? OTelSetup.fromJSON(object.otelSetup) : undefined,
    };
  },

  toJSON(message: ExtendedTraces): unknown {
    const obj: any = {};
    if (message.readinessReason !== 0) {
      obj.readinessReason = extendedTracesReadinessReasonToJSON(message.readinessReason);
    }
    if (message.config !== undefined) {
      obj.config = ExtendedTracesConfig.toJSON(message.config);
    }
    if (message.otelSetup !== undefined) {
      obj.otelSetup = OTelSetup.toJSON(message.otelSetup);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExtendedTraces>, I>>(base?: I): ExtendedTraces {
    return ExtendedTraces.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExtendedTraces>, I>>(object: I): ExtendedTraces {
    const message = createBaseExtendedTraces();
    message.readinessReason = object.readinessReason ?? 0;
    message.config = (object.config !== undefined && object.config !== null)
      ? ExtendedTracesConfig.fromPartial(object.config)
      : undefined;
    message.otelSetup = (object.otelSetup !== undefined && object.otelSetup !== null)
      ? OTelSetup.fromPartial(object.otelSetup)
      : undefined;
    return message;
  },
};

function createBaseExtendedTracesConfig(): ExtendedTracesConfig {
  return { behavior: 0 };
}

export const ExtendedTracesConfig: MessageFns<ExtendedTracesConfig> = {
  encode(message: ExtendedTracesConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.behavior !== 0) {
      writer.uint32(8).int32(message.behavior);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExtendedTracesConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExtendedTracesConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.behavior = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExtendedTracesConfig {
    return { behavior: isSet(object.behavior) ? extendedTracesBehaviorFromJSON(object.behavior) : 0 };
  },

  toJSON(message: ExtendedTracesConfig): unknown {
    const obj: any = {};
    if (message.behavior !== 0) {
      obj.behavior = extendedTracesBehaviorToJSON(message.behavior);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExtendedTracesConfig>, I>>(base?: I): ExtendedTracesConfig {
    return ExtendedTracesConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExtendedTracesConfig>, I>>(object: I): ExtendedTracesConfig {
    const message = createBaseExtendedTracesConfig();
    message.behavior = object.behavior ?? 0;
    return message;
  },
};

function createBaseSendEvents(): SendEvents {
  return { readinessReason: 0, config: undefined };
}

export const SendEvents: MessageFns<SendEvents> = {
  encode(message: SendEvents, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.readinessReason !== 0) {
      writer.uint32(8).int32(message.readinessReason);
    }
    if (message.config !== undefined) {
      SendEventsConfig.encode(message.config, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendEvents {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendEvents();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.readinessReason = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = SendEventsConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendEvents {
    return {
      readinessReason: isSet(object.readinessReason) ? sendEventsReadinessReasonFromJSON(object.readinessReason) : 0,
      config: isSet(object.config) ? SendEventsConfig.fromJSON(object.config) : undefined,
    };
  },

  toJSON(message: SendEvents): unknown {
    const obj: any = {};
    if (message.readinessReason !== 0) {
      obj.readinessReason = sendEventsReadinessReasonToJSON(message.readinessReason);
    }
    if (message.config !== undefined) {
      obj.config = SendEventsConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendEvents>, I>>(base?: I): SendEvents {
    return SendEvents.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendEvents>, I>>(object: I): SendEvents {
    const message = createBaseSendEvents();
    message.readinessReason = object.readinessReason ?? 0;
    message.config = (object.config !== undefined && object.config !== null)
      ? SendEventsConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSendEventsConfig(): SendEventsConfig {
  return { hasEventKey: false, hasEventApiOriginOverride: false };
}

export const SendEventsConfig: MessageFns<SendEventsConfig> = {
  encode(message: SendEventsConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hasEventKey !== false) {
      writer.uint32(8).bool(message.hasEventKey);
    }
    if (message.hasEventApiOriginOverride !== false) {
      writer.uint32(16).bool(message.hasEventApiOriginOverride);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendEventsConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendEventsConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hasEventKey = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hasEventApiOriginOverride = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendEventsConfig {
    return {
      hasEventKey: isSet(object.hasEventKey) ? globalThis.Boolean(object.hasEventKey) : false,
      hasEventApiOriginOverride: isSet(object.hasEventApiOriginOverride)
        ? globalThis.Boolean(object.hasEventApiOriginOverride)
        : false,
    };
  },

  toJSON(message: SendEventsConfig): unknown {
    const obj: any = {};
    if (message.hasEventKey !== false) {
      obj.hasEventKey = message.hasEventKey;
    }
    if (message.hasEventApiOriginOverride !== false) {
      obj.hasEventApiOriginOverride = message.hasEventApiOriginOverride;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendEventsConfig>, I>>(base?: I): SendEventsConfig {
    return SendEventsConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendEventsConfig>, I>>(object: I): SendEventsConfig {
    const message = createBaseSendEventsConfig();
    message.hasEventKey = object.hasEventKey ?? false;
    message.hasEventApiOriginOverride = object.hasEventApiOriginOverride ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
